### ISSUE TITLE
I had a issue. 

### ISSUE THREAD

**Issue by jeenhyung** [kenzanlabs/kubernetes-ci-cd#107]
on part2

I clicked 'Build Now' button on Jenkins. then successed. all changed to green(build, push, deploy).
But, hello-kenzan deployment occurred an error.
New docker image tag was '387ecb8'. 
but, - image: 127.0.0.1:30400/hello-kenzan:latest in 'applications/hello-kenzan/k8s/deployment.yaml' file.

error message : 
`Failed to pull image "127.0.0.1:30400/hello-kenzan:latest": rpc error: code = Unknown desc = Error response from daemon: manifest for 127.0.0.1:30400/hello-kenzan:latest not found`

Not found hello-kenzan:latest..
How to modify latest to <tag>?

**Comment by davidzuluagae** [comment]
Hello,

first off I'd like to know if you are following the guide step by step from the very first part, please confirm that's correct for me.

the way tags are being updated by Jenkins is actually a functionality from kubernetes CD plugin (https://github.com/jenkinsci/kubernetes-cd-plugin) which allows for variable substitution from the Jenkinsfile.

I couldn't replicate the problem you're having, the deployment has the right tag on it for me, but I'd love to work this out with you and try to identify the problem, so please let me know if there's more information you can provide me.

Thanks for submitting the issue.

David Z

**Comment by davidzuluagae** [comment]
hello @jeenhyung, we've just merged a PR that should fix the issue you've reported. I'm going to close this issue for now, but update your fork with the new changes and see if it works for you now. Feel free to open a new issue otherwise.

Thank you!
David Z
