### ISSUE TITLE
kubectl apply -f manifests/registry.yaml fails - too older version for latest kubectl.

### ISSUE THREAD

**Issue by mchalep** [kenzanlabs/kubernetes-ci-cd#123]
Hi,
When I try to run the following:  kubectl apply -f manifests/registry.yaml 

I get the following:
error: unable to recognize "manifests/registry.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

I read extensions/v1beta1 is incorrect and should be apps/v1 since Kubernetes 1.9. I am running the latest version - 1.16 and changing this still fails and outputs:  Deployment.spec): missing required field "selector"

It appears that this file is out of date also and would be very grateful if this could be updated. I am new to Kubernetes and would like to continue following the web article currently available.

Cheers

Patrick

**Comment by mchalep** [comment]
Fixed - Modified this section in the YAML file to look like this:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      run: registry
  replicas: 1
  template:
    metadata:
      labels:
        run: registry
    spec:

kubectl apply -f manifests/registry.yaml
persistentvolume/registry unchanged
persistentvolumeclaim/registry-claim unchanged
service/registry unchanged
service/registry-ui unchanged
deployment.apps/registry created

**Comment by jredondo** [comment]
Thank you @mchalep 
Could you please point me to the docs you found for this? Could you please edit your post with the proper indentation? Also, this might worth a PR. 
Thanks in advance.

**Comment by jredondo** [comment]
Here the diff of the fix that worked for me:
```
diff --git a/manifests/registry.yaml b/manifests/registry.yaml
index d151919..f56f912 100644
--- a/manifests/registry.yaml
+++ b/manifests/registry.yaml
@@ -60,7 +60,8 @@ spec:
   type: NodePort
 ---
 
-apiVersion: extensions/v1beta1
+#apiVersion: extensions/v1beta1
+apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: registry
@@ -101,4 +102,7 @@ spec:
           path: /var/run/docker.sock
       - name: registry-persistent-storage
         persistentVolumeClaim:
-          claimName: registry-claim
\ No newline at end of file
+          claimName: registry-claim
+  selector:
+    matchLabels:
+      app: registry

```
Taken from here: https://github.com/pires/kubernetes-elasticsearch-cluster/issues/220
