### ISSUE TITLE
kubectl apply -f manifests/registry.yaml fails

### ISSUE THREAD

**Issue by mchalep** [kenzanlabs/kubernetes-ci-cd#124]
Hi,

When I try to run the following: kubectl apply -f manifests/registry.yaml

I get the following:
error: unable to recognize "manifests/registry.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

I read extensions/v1beta1 is incorrect and should be apps/v1 since Kubernetes 1.9. I am running the latest version - 1.16 and changing this still fails and outputs: Deployment.spec): missing required field "selector"

I had a go at updating the yaml file, which I thought had fixed the problem but when performing the next step which is:   minikube service registry-ui

The web page opens but the service isn't running - Unable to connect
Firefox can’t establish a connection to the server at 192.168.99.101:30371.

It appears that this file is out of date also and would be very grateful if this could be updated. I am new to Kubernetes and would like to continue following the web article currently available.

Cheers

Patrick

**Comment by mchalep** [comment]
Solved: To fix this issue the following changes were required to "manifests/registry.yaml".

apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  labels:
    app: registry
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
   matchLabels:
    app: registry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: registry
        tier: registry
    spec:

minikube service registry-ui - opens browser and now loads content after these changes.

Patrick

**Comment by astrozyk** [comment]
This shouldn't be closed since it was never fixed upstream. I just ran into the same issue trying to do this project and I did not see this until afterwards. Please re-open until it is fixed on master @mchalep
