### ISSUE TITLE
etcd not registering as thirdpartyresource

### ISSUE THREAD

**Issue by jknsware** [kenzanlabs/kubernetes-ci-cd#29]
I'm a complete kubernetes n00b so please bare with me. As I'm working on Part 3, the scripts/etcd.sh script runs:
`echo "installing etcd operator"`
`kubectl  create -f https://raw.githubusercontent.com/coreos/etcd-operator/master/example/deployment.yaml`
`kubectl  rollout status -f https://raw.githubusercontent.com/coreos/etcd-operator/master/example/deployment.yaml`
`until kubectl  get thirdpartyresource cluster.etcd.coreos.com`
`do`
`    echo "waiting for operator"`
`    sleep 2`
`done`

I get the following error message:
`Error from server (NotFound): thirdpartyresources.extensions "cluster.etcd.coreos.com" not found`
`waiting for operator`

Running `kubectl get thirdpartyresource` returns `No resources found`. Doesn't matter how long I wait for something to register.

I found a similar walk-through for etcd at [IBM's Developer Site](https://developer.ibm.com/recipes/tutorials/orchestrate-secure-etcd-deployments-with-kubernetes-and-operator/) that references a pinned version of etcd-operator.
- IBM pinned version = quay.io/coreos/etcd-operator:v0.2.6
- Manifest from coreos = quay.io/coreos/etcd-operator:v0.5.0

If I use the manifest from that link, I get a thirdpartyresource result after about 30s. Is this a result of something changing with etcd?

**Comment by jknsware** [comment]
This appears to be something to do with the differences in how things are done in v.0.4.2 vs in v.0.5.0. If I switch to using the v.0.4.2 etcd-operator yml files, everything seems to be working better. Sadly, I don't know enough about kubernetes/etcd/coreos/etc yet to figure out why.

- [etcd-operator v.0.5.0](https://github.com/coreos/etcd-operator/tree/master/example)
- [etcd-operator v.0.4.2](https://github.com/coreos/etcd-operator/tree/v0.4.2/example)

**Comment by jknsware** [comment]
Digging farther, this is listed as a breaking change with [etc-operator v.0.5.0.](https://github.com/coreos/etcd-operator/commit/e660e2a1816adfb1c7ef4b16c50e9d6809e7cb9f).

**Comment by mornindew** [comment]
Thank you Jknsware.    Not bad for a "n00b' either.   I will take a look at it to see if we can get it defined as a CRD instead of a third party.    Thanks for bringing this to our attention.

**Comment by JustinT294** [comment]
Resolved with https://github.com/kenzanlabs/kubernetes-ci-cd/pull/32
