### ISSUE TITLE
scripts/etcd.sh correct?

### ISSUE THREAD

**Issue by bryanleekw** [kenzanlabs/kubernetes-ci-cd#36]
I ran etcd.sh file, but failed many times. So I checked that etcd/etcd cluster service/etcd service shall be created. However, it seems the scripts only can create operator and pod, but where to check etcd cluster works fine? 
Anyone have experience on this? 

################################
# Install etcd
################################
echo "installing etcd operator"
kubectl create -f manifests/deployment.yaml
kubectl rollout status -f manifests/deployment.yaml

until kubectl get thirdpartyresource cluster.etcd.coreos.com
do
    echo "waiting for operator"
    sleep 2
done

################################
# create etcd cluster service
################################
echo "pausing for 10 seconds for operator to settle"
sleep 10

kubectl  create -f manifests/example-etcd-cluster.yaml

echo "installing etcd cluster service"
kubectl  create -f manifests/service.json

################################
# etcd cluster 
################################
echo "waiting for etcd cluster to turnup"

until kubectl  get pod example-etcd-cluster-0002
do
    echo "waiting for etcd cluster to turnup"
    sleep 2
done

**Comment by davidzuluagae** [comment]
will be revisited in https://github.com/kenzanlabs/kubernetes-ci-cd/issues/54
