### ISSUE TITLE
kr8sswordz unable to load puzzle

### ISSUE THREAD

**Issue by bryanleekw** [kenzanlabs/kubernetes-ci-cd#37]
Hi all,
I have successfully done exercise 1 in part 3, but when I start the browser, the page can show kr8ssword page, but keep looping without showing puzzle. The puzzle keep showing a loop gif picture. Please help how to troubelshoot

https://www.linux.com/blog/learn/chapter/intro-to-kubernetes/2017/6/run-and-scale-distributed-crossword-puzzle-app-cicd-kubernetes-part-3

**Comment by s7aesis** [comment]
Same here. I see in my browser console: `TypeError: NetworkError when attempting to fetch resource.`, and the crossword never loads in. I am running kubernetes 1.10.0

**Comment by davidzuluagae** [comment]
There are multiple reasons why this issue might be happening, but in any case it will be revisited in https://github.com/kenzanlabs/kubernetes-ci-cd/issues/55 and https://github.com/kenzanlabs/kubernetes-ci-cd/issues/56
