### ISSUE TITLE
Unable to pull puzzle images from local repository

### ISSUE THREAD

**Issue by bryanleekw** [kenzanlabs/kubernetes-ci-cd#38]
I found that unable to pull images from the repository, but I can access repository portal and other images can pull from local repository. So, it is strange and here is the log

bryanleekw@nb1:~$ kubectl describe pod puzzle-85f88bffcf-x5n59
Name:           puzzle-85f88bffcf-x5n59
Namespace:      default
Node:           minikube/192.168.99.100
Start Time:     Fri, 19 Jan 2018 10:05:23 +0800
Labels:         app=puzzle
                pod-template-hash=4194469979
                tier=puzzle
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"puzzle-85f88bffcf","uid":"0c562b6a-fc56-11e7-b1ed-080027302ed5",...
Status:         Running
IP:             172.17.0.13
Controlled By:  ReplicaSet/puzzle-85f88bffcf
Containers:
  puzzle:
    Container ID:   docker://e51549e596ecbd437d88edc5920f45661a8eb79299c8a80d076f79a7d4e28719
    Image:          127.0.0.1:30400/puzzle:8a7b5cb
    Image ID:       docker-pullable://127.0.0.1:30400/puzzle@sha256:118e62bb5f0177f9e2972be1a58974a4625592065c0521d1917dd15aa63ba600
    Port:           3000/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Sat, 20 Jan 2018 20:47:26 +0800
      Finished:     Sat, 20 Jan 2018 20:50:01 +0800
    Ready:          False
    Restart Count:  19
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4f4ds (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-4f4ds:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4f4ds
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age                 From               Message
  ----     ------                 ----                ----               -------
  Normal   SandboxChanged         10h                 kubelet, minikube  Pod sandbox changed, it will be killed and re-created.
  Normal   SuccessfulMountVolume  10h                 kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-4f4ds"
  Normal   SuccessfulMountVolume  10h                 kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-4f4ds"
  Warning  Failed                 10h (x2 over 10h)   kubelet, minikube  Failed to pull image "127.0.0.1:30400/puzzle:8a7b5cb": rpc error: code = Unknown desc = Error response from daemon: Get http://127.0.0.1:30400/v2/: dial tcp 127.0.0.1:30400: getsockopt: connection refused
  Normal   BackOff                10h (x2 over 10h)   kubelet, minikube  Back-off pulling image "127.0.0.1:30400/puzzle:8a7b5cb"
  Normal   Pulling                10h (x3 over 10h)   kubelet, minikube  pulling image "127.0.0.1:30400/puzzle:8a7b5cb"
  Normal   Pulled                 10h                 kubelet, minikube  Successfully pulled image "127.0.0.1:30400/puzzle:8a7b5cb"
  Normal   Created                10h                 kubelet, minikube  Created container
  Normal   Started                10h                 kubelet, minikube  Started container
  Normal   Killing                10h                 kubelet, minikube  Killing container with id docker://puzzle:FailedPostStartHook
  Warning  FailedPostStartHook    10h (x2 over 10h)   kubelet, minikube  
  Warning  BackOff                10h (x26 over 10h)  kubelet, minikube  Back-off restarting failed container
  Warning  FailedSync             10h (x43 over 10h)  kubelet, minikube  Error syncing pod
  Normal   SuccessfulMountVolume  10h                 kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-4f4ds"
  Normal   SandboxChanged         10h                 kubelet, minikube  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling                10h                 kubelet, minikube  pulling image "127.0.0.1:30400/puzzle:8a7b5cb"
  Warning  Failed                 10h                 kubelet, minikube  Failed to pull image "127.0.0.1:30400/puzzle:8a7b5cb": rpc error: code = Unknown desc = Error response from daemon: Get http://127.0.0.1:30400/v2/: dial tcp 127.0.0.1:30400: getsockopt: connection refused
  Warning  FailedSync             10h                 kubelet, minikube  Error syncing pod
  Normal   SuccessfulMountVolume  10h                 kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-4f4ds"
  Warning  Failed                 10h                 kubelet, minikube  Failed to pull image "127.0.0.1:30400/puzzle:8a7b5cb": rpc error: code = Unknown desc = Error response from daemon: Get http://127.0.0.1:30400/v2/: dial tcp 127.0.0.1:30400: getsockopt: connection refused
  Normal   Pulling                9h (x3 over 10h)    kubelet, minikube  pulling image "127.0.0.1:30400/puzzle:8a7b5cb"
  Normal   Pulled                 9h (x2 over 10h)    kubelet, minikube  Successfully pulled image "127.0.0.1:30400/puzzle:8a7b5cb"
  Normal   Created                9h (x2 over 10h)    kubelet, minikube  Created container
  Normal   Started                9h (x2 over 10h)    kubelet, minikube  Started container
  Normal   Killing                9h (x2 over 10h)    kubelet, minikube  Killing container with id docker://puzzle:FailedPostStartHook
  Warning  BackOff                9h (x4 over 10h)    kubelet, minikube  Back-off restarting failed container
  Warning  FailedSync             9h (x7 over 10h)    kubelet, minikube  Error syncing pod
  Warning  FailedPostStartHook    9h (x3 over 10h)    kubelet, minikube  
  Warning  FailedPreStopHook      9h                  kubelet, minikube  
  Normal   SuccessfulMountVolume  19m                 kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-4f4ds"
  Normal   SandboxChanged         19m                 kubelet, minikube  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling                19m                 kubelet, minikube  pulling image "127.0.0.1:30400/puzzle:8a7b5cb"
  Normal   SuccessfulMountVolume  17m                 kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-4f4ds"
  Warning  Failed                 17m (x2 over 17m)   kubelet, minikube  Failed to pull image "127.0.0.1:30400/puzzle:8a7b5cb": rpc error: code = Unknown desc = Error response from daemon: Get http://127.0.0.1:30400/v2/: dial tcp 127.0.0.1:30400: getsockopt: connection refused
  Normal   BackOff                16m (x2 over 17m)   kubelet, minikube  Back-off pulling image "127.0.0.1:30400/puzzle:8a7b5cb"
  Normal   Pulling                16m (x3 over 17m)   kubelet, minikube  pulling image "127.0.0.1:30400/puzzle:8a7b5cb"
  Normal   Pulled                 16m                 kubelet, minikube  Successfully pulled image "127.0.0.1:30400/puzzle:8a7b5cb"
  Normal   Created                16m                 kubelet, minikube  Created container
  Normal   Started                16m                 kubelet, minikube  Started container
  Warning  FailedPreStopHook      16m                 kubelet, minikube  
  Warning  BackOff                15m (x3 over 15m)   kubelet, minikube  Back-off restarting failed container
  Warning  FailedPostStartHook    10m (x2 over 16m)   kubelet, minikube  
  Warning  FailedSync             7m (x34 over 17m)   kubelet, minikube  Error syncing pod
  Normal   Killing                2m (x3 over 15m)    kubelet, minikube  Killing container with id docker://puzzle:FailedPostStartHook

**Comment by davidzuluagae** [comment]
I apologize we didn't address this in a timely manner. We're working on updating the tutorial, so please stay tuned and feel free to give it another try after we rollout the update. I'm now going to close this issue as we'll work on make it all work again.
