### ISSUE TITLE
Error creating proxy with socat docker image

### ISSUE THREAD

**Issue by miksonx** [kenzanlabs/kubernetes-ci-cd#43]
When running following command

docker stop socat-registry; docker rm socat-registry; docker run -d -e "REGIP=minikube ip" --name socat-registry -p 30400:5000 chadmoon/socat:latest bash -c "socat TCP4-LISTEN:5000,fork,reuseaddr TCP4:minikube ip:30400"

docker image die and no socat container is running.
Workaround 
Run 
minikube ip 
on command line and replace TCP4:minikube ip:30400 part with  TCP4:IP_RETURNED_IN_CMD:30400

**Comment by davidzuluagae** [comment]
Socat solution will be redefined at https://github.com/kenzanlabs/kubernetes-ci-cd/issues/48
