### ISSUE TITLE
Any chance of an update to 1.8/1.9?

### ISSUE THREAD

**Issue by nukepuppy** [kenzanlabs/kubernetes-ci-cd#44]
Any chance of an update to 1.8/1.9?

the sad part of kubernetes is how fast its evolving!  I could probably lend a hand if cycles allow

**Comment by mornindew** [comment]
That would be great, would love it.  Will be happy to work with you on your PR.  I will grant you write permissions so that you can create a PR.

I am going to get a slack site setup so that we can chat in the community as well.

**Comment by s7aesis** [comment]
I'd like to help too

**Comment by mornindew** [comment]
s7aesis - that would be great.   Both you and Nukepuppy have been given write access.   Feel free to create a feature branch and we can work with you on the PR process.

Stoked that you guys are helping out, appreciate it.

**Comment by s7aesis** [comment]
I created a branch to start updating to kubernetes 1.10 https://github.com/kenzanlabs/kubernetes-ci-cd/tree/kubernetes_v1.10.0

**Comment by davidzuluagae** [comment]
Will revisit at https://github.com/kenzanlabs/kubernetes-ci-cd/issues/50
