### ISSUE TITLE
Privileged Jenkins deployment

### ISSUE THREAD

**Issue by davidzuluagae** [kenzanlabs/kubernetes-ci-cd#53]
Jenkins deployment requires privileged access in order to Read/Write Docker.sock shared as a volume from the host

Temporary workaround:
`chmod 666 /var/run/docker.sock` directly on host

**Comment by mdurandjr** [comment]
I was not able to reproduce a permissions issue with jenkins and /var/run/docker.sock. It is clear that the chadmoon jenkins image is out of date and there are issues with the pipeline plugins. The new docker image should continue to have jenkins run as a privileged user for the purpose of this exercise.

**Comment by davidzuluagae** [comment]
We need to explicit make the necessary changes to ensure that minikube runs docker container runtime and not rkt

**Comment by davidzuluagae** [comment]
https://github.com/kenzanlabs/kubernetes-ci-cd/pull/81
